// The three sample workspaces (FR-01). Their data is generated by
// data/generators/<id>/ and served from /demo/<id>/<table>.parquet (D-026).

export interface Sample {
  id: string;
  /** The made-up business the data belongs to. */
  name: string;
  /** What one row is, plural, for sentences: "59,881 orders". */
  rowNoun: string;
  table: string;
  /** Until the dictionary exists (T12), the column that dates each row. */
  timeColumn: string;
}

export const SAMPLES = [
  {
    id: 'retail',
    name: 'Harbour & Pine',
    rowNoun: 'order lines',
    table: 'orders',
    timeColumn: 'order_date',
  },
  {
    id: 'saas',
    name: 'Slotwise',
    rowNoun: 'account-months',
    table: 'subscriptions',
    timeColumn: 'month',
  },
  {
    id: 'support',
    name: 'Kettle Helpdesk',
    rowNoun: 'tickets',
    table: 'tickets',
    timeColumn: 'created_at',
  },
] as const satisfies readonly Sample[];

export type SampleId = (typeof SAMPLES)[number]['id'];

/** The sample `/` shows. */
export const DEFAULT_SAMPLE: SampleId = 'retail';

export function findSample(id: string): Sample | undefined {
  return SAMPLES.find((s) => s.id === id);
}

export function sampleUrl(sample: Sample): string {
  return `/demo/${sample.id}/${sample.table}.parquet`;
}
